# Project Configuration
project:
  name: "Vietnamese Address Classifier"
  version: "1.0.0"
  team: "TBD"
  competition: "Advanced Algorithms Course Project"

# Performance Requirements
performance:
  max_processing_time: 0.1      # Hard limit (seconds)
  target_avg_time: 0.01         # Performance target (seconds)  
  target_accuracy: 0.85         # Minimum accuracy requirement
  stretch_accuracy: 0.90        # Competitive target

# Algorithm Parameters
normalization:
  remove_diacritics: true
  normalize_whitespace: true
  lowercase: true
  handle_ocr_errors: true

matching:
  max_edit_distance: 2          # Fuzzy matching threshold
  confidence_threshold: 0.8     # Minimum confidence for acceptance
  use_geographic_constraints: true
  enable_hierarchical_matching: true

# Processing Strategy
processing:
  tier_1_exact_matching: true   # Fast exact lookups
  tier_2_pattern_matching: true # Pattern-based parsing
  tier_3_fuzzy_fallback: true   # Fuzzy matching as last resort
  
# Data Paths
data:
  raw_training_data: "data/raw/all_raw.json"
  province_list: "data/raw/list_province"  
  district_list: "data/raw/list_district"
  ward_list: "data/raw/list_ward"
  processed_data: "data/processed/"
  test_data: "data/test/"

# Development Settings
development:
  debug: true
  log_level: "INFO"
  enable_performance_monitoring: true
  save_intermediate_results: true

# Testing Configuration
testing:
  validation_split: 0.2
  performance_test_samples: 1000
  accuracy_test_threshold: 0.85
  timing_test_iterations: 100

# Logging
logging:
  level: "INFO"
  file: "logs/classifier.log"
  performance_log: "logs/performance.log"
  error_log: "logs/errors.log"